# Site settings
title: Bitcoin (BTC) Casinò italiani
email: reception@btccasino.it
description: > # this means to ignore newlines until "baseurl:"
  Bitcoin (BTC) Casinò italiani
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.btccasino.it" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
